services:
 db:
  image: postgres:13
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: temp
    POSTGRES_PASSWORD: temp
    POSTGRES_DB: advcompro_w10 
  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: